// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV9xnCyk29MBbJbNmFjuFpMKf9030LAN4',
    appId: '1:1012248046510:web:bf876a495e32983b6a363f',
    messagingSenderId: '1012248046510',
    projectId: 'healthyapp-dfcc0',
    authDomain: 'healthyapp-dfcc0.firebaseapp.com',
    databaseURL: 'https://healthyapp-dfcc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyapp-dfcc0.firebasestorage.app',
    measurementId: 'G-JNRDLH2PQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPNlxKHjtYIDn1-jUYOf6ZnSEdFkciVAQ',
    appId: '1:1012248046510:android:95888a3204e4c6e06a363f',
    messagingSenderId: '1012248046510',
    projectId: 'healthyapp-dfcc0',
    databaseURL: 'https://healthyapp-dfcc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyapp-dfcc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVvmxtwEAXI4vN2x0cyQueDAqt7blmWUM',
    appId: '1:1012248046510:ios:87ec3f5bca1412406a363f',
    messagingSenderId: '1012248046510',
    projectId: 'healthyapp-dfcc0',
    databaseURL: 'https://healthyapp-dfcc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyapp-dfcc0.firebasestorage.app',
    iosBundleId: 'com.example.healthcareapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVvmxtwEAXI4vN2x0cyQueDAqt7blmWUM',
    appId: '1:1012248046510:ios:87ec3f5bca1412406a363f',
    messagingSenderId: '1012248046510',
    projectId: 'healthyapp-dfcc0',
    databaseURL: 'https://healthyapp-dfcc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyapp-dfcc0.firebasestorage.app',
    iosBundleId: 'com.example.healthcareapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV9xnCyk29MBbJbNmFjuFpMKf9030LAN4',
    appId: '1:1012248046510:web:0d1bfca501f098b06a363f',
    messagingSenderId: '1012248046510',
    projectId: 'healthyapp-dfcc0',
    authDomain: 'healthyapp-dfcc0.firebaseapp.com',
    databaseURL: 'https://healthyapp-dfcc0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'healthyapp-dfcc0.firebasestorage.app',
    measurementId: 'G-XRWC6PTXL6',
  );
}
